# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Equipment
    url: /#solutions
    hasChildren: true
    weight: 50
  - parent: Equipment
    name: Chromium X
    url: equipment/chromium-x/
  - parent: Equipment
    name: Visium CytAssist
    url: equipment/visium-cytassist/
  - parent: Equipment
    name: Xenium Analyzer
    url: equipment/xenium-analyzer/
  - name: Team
    url: team/
    weight: 70
  - name: Contact
    url: contact/
    weight: 90
